`timescale 1ns / 1ps
// Generated by Zou_lab_control.neutral_atom from PulseSequence 'imaging'.
// Clock: 2.5e+08 Hz

module single_shot_sequence(
    input wire clk,
    input wire reset,
    input wire start,
    output wire trap,
    output wire probe,
    output wire qcm_trigger,
    output reg running,
    output reg done
);

    localparam integer EDGE_COUNT = 6;
    localparam integer REPEATS = 1;
    localparam [22:0] FIRST_TICK = 23'd0;
    localparam [2:0] FIRST_MASK = 3'b001;
    localparam integer FIRST_EDGE_INDEX = 1;
    localparam [22:0] START_COUNT = 23'd1;
    reg [22:0] time_count = 0;
    reg [2:0] edge_index = 0;
    reg [0:0] repeat_count = 0;
    reg [2:0] state_mask = 3'b000;
    reg [22:0] edge_tick;
    reg [2:0] edge_mask;
    reg start_prev = 1'b0;
    wire start_edge = start && !start_prev;

    assign trap = state_mask[0];
    assign probe = state_mask[1];
    assign qcm_trigger = state_mask[2];

    always @(*) begin
        case (edge_index)
                0: edge_tick = 23'd0;
                1: edge_tick = 23'd25000;
                2: edge_tick = 23'd25075;
                3: edge_tick = 23'd30075;
                4: edge_tick = 23'd5025000;
                5: edge_tick = 23'd5030000;
            default: edge_tick = 23'd5030000;
        endcase
        case (edge_index)
                0: edge_mask = 3'b001;
                1: edge_mask = 3'b011;
                2: edge_mask = 3'b111;
                3: edge_mask = 3'b011;
                4: edge_mask = 3'b001;
                5: edge_mask = 3'b000;
            default: edge_mask = 3'b000;
        endcase
    end

    always @(posedge clk) begin
        if (reset) begin
            running <= 1'b0;
            done <= 1'b0;
            time_count <= 0;
            edge_index <= 0;
            repeat_count <= 0;
            state_mask <= 3'b000;
            start_prev <= 1'b0;
        end else begin
            start_prev <= start;
            if (start_edge && !running) begin
                running <= 1'b1;
                done <= 1'b0;
                time_count <= START_COUNT;
                edge_index <= FIRST_EDGE_INDEX;
                repeat_count <= 0;
                if (FIRST_TICK == 0) begin
                    state_mask <= FIRST_MASK;
                end else begin
                    state_mask <= 3'b000;
                end
            end else if (running) begin
                done <= 1'b0;
                if (time_count == edge_tick) begin
                    state_mask <= edge_mask;
                    if (edge_index < EDGE_COUNT - 1) begin
                        edge_index <= edge_index + 1'b1;
                    end
                end

                if (time_count >= 23'd5030000) begin
                    if (repeat_count + 1 < REPEATS) begin
                        time_count <= START_COUNT;
                        edge_index <= FIRST_EDGE_INDEX;
                        repeat_count <= repeat_count + 1'b1;
                        if (FIRST_TICK == 0) begin
                            state_mask <= FIRST_MASK;
                        end else begin
                            state_mask <= 3'b000;
                        end
                    end else begin
                        running <= 1'b0;
                        done <= 1'b1;
                        state_mask <= 3'b000;
                    end
                end else begin
                    time_count <= time_count + 1'b1;
                end
            end else begin
                done <= 1'b0;
            end
        end
    end
endmodule
