# Generated by Zou_lab_control.neutral_atom
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS33} [get_ports trap]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports probe]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports qcm_trigger]
set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports clk]
create_clock -period 4 -name clk [get_ports clk]
