"""Standalone image operations that do not require a connected experiment."""

from .calibration import calibrate_sitemap_from_images, calibrate_threshold_from_images
from .detection import detect_image
from .figure_capture import capture_figure_provenance, capture_figure_signals
from .logic import (
    CalibrateReadoutTask,
    CameraMeasurement,
    OccupancyProcessor,
    Measurement,
    Processor,
    LogicNode,
    ScannedMeasurementNode,
    SignalSpec,
    Task,
    describe_shape,
)
from .fidelity import (
    FidelityReport,
    ReferenceLabels,
    SiteFidelity,
    TrainTestSplit,
    characterize_readout,
    reference_labels,
    train_test_split,
)
from .imageio import RunIndex, frame_files, index_run, load_frame, save_frame
from .measurement import (
    MeasurementSpec,
    NFramePlan,
    OtsuFidelityReducer,
    ParamDecl,
    PointReducer,
    ScanAxis,
    ScanResult,
    ScannedMeasurement,
    ShotPlan,
    axis_range_tuple,
)
from .measurement_registry import (
    discovered_specs,
    measurement,
    register_measurement,
    registered_measurements,
    unregister_measurement,
)
from .processor import ProcessorSpec
from .processor_registry import (
    discovered_processor_specs,
    processor,
    register_processor,
    registered_processors,
    unregister_processor,
)
from .task import TaskSpec
from .task_registry import (
    discovered_task_specs,
    register_task,
    registered_tasks,
    task,
    unregister_task,
)
from .temperature import (
    ReleaseRecapturePlan,
    SurvivalReducer,
    TemperatureFit,
    build_release_recapture_pulse,
    fit_temperature,
    release_recapture_survival,
)

__all__ = [
    "axis_range_tuple",
    "build_release_recapture_pulse",
    "calibrate_sitemap_from_images",
    "calibrate_threshold_from_images",
    "capture_figure_provenance",
    "capture_figure_signals",
    "characterize_readout",
    "CameraMeasurement",
    "detect_image",
    "discovered_specs",
    "LogicNode",
    "FidelityReport",
    "fit_temperature",
    "measurement",
    "register_measurement",
    "registered_measurements",
    "unregister_measurement",
    "discovered_processor_specs",
    "processor",
    "register_processor",
    "registered_processors",
    "unregister_processor",
    "ProcessorSpec",
    "discovered_task_specs",
    "task",
    "register_task",
    "registered_tasks",
    "unregister_task",
    "TaskSpec",
    "frame_files",
    "index_run",
    "load_frame",
    "Measurement",
    "Processor",
    "Task",
    "CalibrateReadoutTask",
    "OccupancyProcessor",
    "MeasurementSpec",
    "NFramePlan",
    "OtsuFidelityReducer",
    "ParamDecl",
    "PointReducer",
    "ReferenceLabels",
    "reference_labels",
    "release_recapture_survival",
    "ReleaseRecapturePlan",
    "RunIndex",
    "save_frame",
    "ScanAxis",
    "ScannedMeasurement",
    "ScannedMeasurementNode",
    "ScanResult",
    "ShotPlan",
    "SignalSpec",
    "describe_shape",
    "SiteFidelity",
    "SurvivalReducer",
    "TemperatureFit",
    "train_test_split",
    "TrainTestSplit",
]
