"""MOVED to :mod:`zlc_workbench.pulse_editor.plot_bridge_pulse_gui` (C20 transitional
zone; this shell dies at Z0).

An explicit ALIAS shell rather than a PEP 562 forwarder: every name below IS the moved
object, and two structural guards pin AST features here - the panel-size vocabulary must
be imported from ``zlc_data.panel_size`` by this path, and the pulse-files seam helpers
(``_pulse_files_dir``/``PULSE_FILES_ENV``) must resolve through this module.
"""

from zlc_data.panel_size import PANEL_SIZES

from zlc_workbench.pulse_editor.plot_bridge_pulse_gui import (  # noqa: F401
    __all__,
    TIME_UNITS,
    DURATION_UNITS,
    DELAY_UNITS,
    _delay_eligible_position,
    UNIT_TO_NS,
    ROW_HEIGHT,
    CHANNEL_LABEL_WIDTH,
    TIME_UNIT_WIDTH,
    HIDE_BUTTON_WIDTH,
    PANEL_TOP_HEIGHT,
    CHANNEL_ROW_SPACING,
    PERIOD_CARD_WIDTH,
    DEFAULT_WINDOW_RATIO,
    DEFAULT_HARDWARE_CLOCK_HZ,
    DEFAULT_TIME_STEP_NS,
    SUMMARY_DEBOUNCE_MS,
    PREVIEW_DEBOUNCE_MS,
    PULSE_FILES_ENV,
    _px,
    _font_metrics,
    _row_height,
    _row_spacing,
    _channel_label_width,
    _channel_name_edit_width,
    _time_unit_width,
    _hide_button_width,
    _panel_top_height,
    _card_gutter,
    _period_card_width,
    _default_pulse_name,
    _pulse_files_dir,
    _safe_file_stem,
    _period_duration_text,
    _period_control_width,
    _is_slot_expr,
    _slot_index_of_expr,
    _api_number,
    _scan_slot_label,
    _format_scan_progress,
    _template_column_stack,
    _template_grid,
    _default_scan_code,
    _format_clock_text,
    _delay_cap_text,
    _bus_mode_combo_width,
    _set_duration_unit_combo,
    _normalize_bus_value_text,
    _unit_resolution,
    _bus_key,
    _bus_mode_title,
    _bus_mode_value,
    _is_bus_key,
    _display_rows,
    _port_visibility,
    _hidden_active_ports,
    _display_row_label,
    _summary_time_text,
    _set_fixed_height,
    _set_form_label_geometry,
    _add_labeled_widget,
    _form_control_cell,
    _channel_row_height,
    _elide_text,
    PulseStateUIManager,
    PeriodCard,
    _DragItem,
    PulseDragContainer,
    RepeatBracket,
    ChannelNamesPanel,
    ChannelPanel,
    PulseSequenceEditor,
    show_pulse_gui,
)
