"""Renderer-free figure documents, view contracts, and evaluation."""

from .codec import (
    decode_figure_document,
    decode_view_spec,
    encode_figure_document,
    encode_view_spec,
    figure_document_from_tree,
    figure_document_to_tree,
    view_spec_from_tree,
    view_spec_to_tree,
)
from .contract import (
    CURVE_CONTRACT,
    DocumentViewContract,
    HISTOGRAM_CONTRACT,
    IMAGE_CONTRACT,
    METER_CONTRACT,
    PULSE_CONTRACT,
    VIEW_CONTRACTS,
    contract_for,
    dataset_contract_for,
    dataset_axes,
    display_axis_indices,
    fit_single_panel_presentation,
    selection_fit_view_projection,
    validate_view_spec,
)
from .evaluate import (
    FigureEvaluationCancelled,
    FigureEvaluationDeadlineExceeded,
    FigureEvaluationError,
    FigureEvaluator,
    ResolvedDataset,
    ResolvedDatasetMap,
)
from .model import (
    DATASET_VIEW_INTENTS,
    AxisAddress,
    AxisResolution,
    AxisRolePolicy,
    AxisViewBinding,
    AxisViewRole,
    DatasetDescriptor,
    DatasetId,
    DecisionReason,
    DisplayReduction,
    DisplayReductionMethod,
    DisplaySlot,
    EvaluatedAxis,
    EvaluatedCell,
    EvaluatedCurve,
    EvaluatedFigureData,
    EvaluatedHistogram,
    EvaluatedImage,
    EvaluatedInput,
    EvaluatedLayer,
    EvaluatedMeter,
    EvaluatedSeries,
    FigureDocument,
    FigureLayer,
    FigureSelection,
    FixedIndex,
    LatestNonempty,
    ReductionResolution,
    RepeatViewMode,
    SampleCoordinates,
    SuggestionStatus,
    ViewAlternative,
    ViewContract,
    ViewIntent,
    ViewPreferences,
    ViewSpec,
    ViewSuggestion,
)
from .suggest import suggest_fit_view, suggest_view


__all__ = [
    "AxisAddress", "AxisResolution", "AxisRolePolicy",
    "AxisViewBinding", "AxisViewRole", "CURVE_CONTRACT", "DATASET_VIEW_INTENTS",
    "DatasetDescriptor", "DocumentViewContract",
    "DatasetId", "DecisionReason", "DisplayReduction", "DisplayReductionMethod",
    "DisplaySlot", "EvaluatedAxis", "EvaluatedCell", "EvaluatedCurve",
    "EvaluatedFigureData", "EvaluatedHistogram", "EvaluatedImage", "EvaluatedInput",
    "EvaluatedLayer", "EvaluatedMeter", "EvaluatedSeries", "FigureDocument",
    "FigureEvaluationCancelled", "FigureEvaluationDeadlineExceeded",
    "FigureEvaluationError",
    "FigureEvaluator", "FigureLayer", "FigureSelection",
    "FixedIndex", "HISTOGRAM_CONTRACT", "IMAGE_CONTRACT", "LatestNonempty",
    "METER_CONTRACT", "PULSE_CONTRACT", "ReductionResolution", "RepeatViewMode", "ResolvedDataset",
    "ResolvedDatasetMap", "SampleCoordinates", "SuggestionStatus", "VIEW_CONTRACTS",
    "ViewAlternative", "ViewContract", "ViewIntent", "ViewPreferences", "ViewSpec",
    "ViewSuggestion", "contract_for", "dataset_contract_for", "dataset_axes", "display_axis_indices", "fit_single_panel_presentation", "decode_figure_document",
    "decode_view_spec", "encode_figure_document", "encode_view_spec",
    "figure_document_from_tree", "figure_document_to_tree", "suggest_fit_view", "suggest_view",
    "selection_fit_view_projection", "validate_view_spec", "view_spec_from_tree", "view_spec_to_tree",
]
