"""The sole public Qt widget and Qt-style surface for the current frontend.

Import this leaf explicitly.  The headless :mod:`zlc_frontend` package root does
not re-export it and therefore never loads PyQt as a side effect.
"""

from ..image_view import ImageViewportTransform
from ..selector import (
    CurveInteractionIntent,
    CurveRangeGesture,
    CurveViewportCommit,
    HistogramInteractionIntent,
    HistogramRangeGesture,
    HistogramViewportCommit,
    ImageColorLimitsCommit,
    ImageInteractionCommit,
    ImageViewportCommit,
    PanelInteractionOrigin,
    RectangleGesture,
)
from .axis_navigator import AxisLayoutNavigator
from .board import QtImageBoard, QtOwnerWake, QtRasterBoard
from .form import FORM_WIDGET_HANDLERS, FluentParameterForm, FormWidgetHandler
from .fit_authoring import FitAuthoringPane
from .signal_expr_widget import SignalExprWidget
from .pulse_slots_widget import PulseSlotsWidget
from .logic_node_row import LogicNodeRow
from .flow_graph_view import FlowGraphView
from .signal_picker import (
    coerce_short_labels,
    fill_grouped_signal_combo,
    grouped_signal_items,
    read_editable_combo,
    signal_state,
    signal_tree_groups,
)
from .display_editor import (
    FluentRevisionedFormEditor,
    runtime_range_placeholders,
    sync_revisioned_form_editors,
)
from .fluent import (
    ElidedLabel,
    FluentButton,
    FluentCheckBox,
    FluentCodeEdit,
    FluentComboBox,
    FluentDoubleSpinBox,
    FluentFloatingEditor,
    FluentFormGrid,
    FluentFrame,
    FluentGroupBox,
    FluentInputDialog,
    FluentLabel,
    FluentLabeledField,
    FluentLineEdit,
    FluentPathEdit,
    FluentPopup,
    FluentReadoutEdit,
    FluentReadoutMultiline,
    FluentSettingsPopupAnchor,
    FluentScanDot,
    FluentScanLineEdit,
    FluentScrollArea,
    FluentSectionLabel,
    FluentSettingRow,
    FluentSpinBox,
    FluentStatusDot,
    FluentStatusStrip,
    FluentSwitch,
    FluentTabWidget,
    FluentTreeComboBox,
    FluentTriStateToggle,
    FluentWindow,
    Metrics,
    align_to_resolution,
    apply_fluent_scrollbars,
    arbitrate_status_line,
    batched_updates,
    center_window_on_primary_screen,
    eng_mantissa_prefix,
    ensure_qt_app,
    float2str_eng,
    fluent_confirm,
    fluent_font_size,
    fluent_message,
    fluent_scale,
    fluent_scrollbar_stylesheet,
    fluent_scrollbar_thickness,
    fluent_spinbox_stylesheet,
    fluent_text_prompt,
    fluent_text_width,
    fluent_widget_stylesheet,
    format_compact_number,
    launch_fluent_window,
    mark_scan_field,
    measure_text_width,
    muted_note_label,
    popup_gap,
    show_fluent_popup_for_anchor,
    release_window,
    resolve_fluent_auto_scale,
    retain_window,
    scaled_px,
    screen_fit_window_size,
    set_fluent_scale,
    setting_label_width,
    signals_blocked,
    status_dot_stylesheet,
    stroke_card_border,
    window_pad,
)
from .style import (
    ACCENT,
    API_VIOLET,
    API_VIOLET_DARK,
    BG,
    CARD_PAD,
    CARD_TITLE_PX,
    COMBO_TRI_SIZE,
    COMBO_WIDTH,
    DIVIDER,
    EDIT_PADDING_H,
    FLUENT_SCALE_MAX,
    FLUENT_SCALE_MIN,
    FONT,
    FONT_SIZE,
    GREEN,
    GREY,
    HINT,
    HOVER,
    MUTED_LABEL_STYLE,
    ORANGE,
    ORANGE_DARK,
    ORANGE_TINT,
    PADDING_H,
    PADDING_V,
    PLACEHOLDER,
    RADIUS,
    RED,
    STEP_WIDTH,
    TEXT,
    TIMELINE_ACTIVE_FILL_RGBA,
    TIMELINE_AXIS_TEXT,
    TIMELINE_BACKGROUND,
    TIMELINE_EMPTY_TEXT,
    TIMELINE_GRID,
    TIMELINE_PERIOD_BACKGROUNDS,
    TIMELINE_PERIOD_TEXT,
    TIMELINE_REPEAT,
    TIMELINE_ROW_TEXT,
    TIMELINE_TITLE_TEXT,
    TIMELINE_TRACE,
    TITLE_LEFT_INSET,
    WINDOW_PAD,
    WINDOW_SCREEN_FRACTION,
    YELLOW,
    raster_placeholder_stylesheet,
)


__all__ = [
    "FlowGraphView",
    "LogicNodeRow",
    "LogicNodeEditor",
    "MeasurementPanel",
    "PulseSlotsWidget",
    "SignalExprWidget",
    "ACCENT",
    "API_VIOLET",
    "API_VIOLET_DARK",
    "AxisLayoutNavigator",
    "BG",
    "CARD_PAD",
    "CARD_TITLE_PX",
    "COMBO_TRI_SIZE",
    "COMBO_WIDTH",
    "DIVIDER",
    "EDIT_PADDING_H",
    "ElidedLabel",
    "FLUENT_SCALE_MAX",
    "FLUENT_SCALE_MIN",
    "FONT",
    "FONT_SIZE",
    "FORM_WIDGET_HANDLERS",
    "FluentButton",
    "FluentCheckBox",
    "FluentCodeEdit",
    "FluentComboBox",
    "FluentDoubleSpinBox",
    "FluentFloatingEditor",
    "FitAuthoringPane",
    "FluentFormGrid",
    "FluentFrame",
    "FluentGroupBox",
    "FluentRevisionedFormEditor",
    "runtime_range_placeholders",
    "sync_revisioned_form_editors",
    "FluentInputDialog",
    "FluentLabel",
    "FluentLabeledField",
    "FluentLineEdit",
    "FluentPathEdit",
    "FluentParameterForm",
    "FluentPopup",
    "FluentReadoutEdit",
    "FluentReadoutMultiline",
    "FluentSettingsPopupAnchor",
    "FluentScanDot",
    "FluentScanLineEdit",
    "FluentScrollArea",
    "FluentSectionLabel",
    "FluentSettingRow",
    "FluentSpinBox",
    "FluentStatusDot",
    "FluentStatusStrip",
    "FluentSwitch",
    "FluentTabWidget",
    "FluentTreeComboBox",
    "FluentTriStateToggle",
    "FluentWindow",
    "FormWidgetHandler",
    "GREEN",
    "GREY",
    "HINT",
    "HOVER",
    "ImageViewportTransform",
    "ImageColorLimitsCommit",
    "ImageInteractionCommit",
    "ImageViewportCommit",
    "CurveInteractionIntent",
    "CurveRangeGesture",
    "CurveViewportCommit",
    "HistogramInteractionIntent",
    "HistogramRangeGesture",
    "HistogramViewportCommit",
    "PanelInteractionOrigin",
    "MUTED_LABEL_STYLE",
    "Metrics",
    "ORANGE",
    "ORANGE_DARK",
    "ORANGE_TINT",
    "PADDING_H",
    "PADDING_V",
    "PLACEHOLDER",
    "QtImageBoard",
    "QtOwnerWake",
    "QtRasterBoard",
    "RADIUS",
    "RectangleGesture",
    "RED",
    "STEP_WIDTH",
    "TEXT",
    "TIMELINE_ACTIVE_FILL_RGBA",
    "TIMELINE_AXIS_TEXT",
    "TIMELINE_BACKGROUND",
    "TIMELINE_EMPTY_TEXT",
    "TIMELINE_GRID",
    "TIMELINE_PERIOD_BACKGROUNDS",
    "TIMELINE_PERIOD_TEXT",
    "TIMELINE_REPEAT",
    "TIMELINE_ROW_TEXT",
    "TIMELINE_TITLE_TEXT",
    "TIMELINE_TRACE",
    "TITLE_LEFT_INSET",
    "WINDOW_PAD",
    "WINDOW_SCREEN_FRACTION",
    "YELLOW",
    "align_to_resolution",
    "apply_fluent_scrollbars",
    "arbitrate_status_line",
    "batched_updates",
    "center_window_on_primary_screen",
    "eng_mantissa_prefix",
    "ensure_qt_app",
    "float2str_eng",
    "fluent_confirm",
    "fluent_font_size",
    "fluent_message",
    "fluent_scale",
    "fluent_scrollbar_stylesheet",
    "fluent_scrollbar_thickness",
    "fluent_spinbox_stylesheet",
    "fluent_text_prompt",
    "fluent_text_width",
    "fluent_widget_stylesheet",
    "format_compact_number",
    "launch_fluent_window",
    "mark_scan_field",
    "measure_text_width",
    "muted_note_label",
    "popup_gap",
    "show_fluent_popup_for_anchor",
    "release_window",
    "raster_placeholder_stylesheet",
    "resolve_fluent_auto_scale",
    "retain_window",
    "scaled_px",
    "screen_fit_window_size",
    "set_fluent_scale",
    "setting_label_width",
    "signals_blocked",
    "coerce_short_labels",
    "fill_grouped_signal_combo",
    "grouped_signal_items",
    "read_editable_combo",
    "signal_state",
    "signal_tree_groups",
    "status_dot_stylesheet",
    "stroke_card_border",
    "window_pad",
]

# The salvaged legacy param-form module lives INSIDE this package (it is Qt
# code, and qt_widgets is the package's one Qt owner).  Imported LAST so its
# own `from zlc_frontend.qt_widgets import ...` finds every facade name bound.
# Reachable as an attribute like `fluent`/`board`; deliberately NOT in
# __all__ - the legacy shim is its only sanctioned outside consumer.
from . import param_widgets  # noqa: E402,F401

# The console's background render worker.  Qt-only (no Matplotlib), so qt_widgets is where the
# placement axiom puts it; bound here like ``param_widgets`` so consumers reach it as an
# ATTRIBUTE of the package rather than importing the submodule path, which the package's own
# guard forbids from outside.

# The per-panel Analysis controls (fit + ROI), salvaged out of the console shell.  Pure Qt, so
# qt_widgets is where the placement axiom puts them; bound as an attribute for the same reason
# as the two above -- the package's own guard forbids outside consumers from deep-importing a
# submodule path.
from . import analysis_controls  # noqa: E402,F401

# The two editor widgets salvaged from the console shell.  Imported AFTER ``param_widgets``:
# they reach it via ``from . import param_widgets``, which needs the registry importable, and
# the registry itself reads facade names -- so these must sit at the tail like it does.
from .measurement_panel import MeasurementPanel  # noqa: E402
from .logic_node_editor import LogicNodeEditor  # noqa: E402
