"""The complete Camera Measurement logic-node attachment."""

from .binding import CameraCaptureBindingRequest, bind_camera_measurement
from .definition import (
    CAMERA_FRAME_OUTPUT_CONTRACT_ID,
    CAMERA_MEASUREMENT_DEFINITION,
    CAMERA_MEASUREMENT_KEY,
    CAMERA_MEASUREMENT_ROLE_ORDER,
    DEFAULT_CAMERA_FRAMES_PER_CYCLE,
    DEFAULT_CAMERA_MEASUREMENT_REPEAT,
    DEFAULT_CAMERA_MEASUREMENT_ROLE,
    DEFAULT_CAMERA_MONITOR_HISTORY_CYCLES,
    MINIMUM_CAMERA_FRAMES_PER_CYCLE,
    MINIMUM_CAMERA_MEASUREMENT_REPEAT,
    CameraMeasurementDescriptor,
    CameraMeasurementRequest,
    build_camera_measurement_request_from_authoring,
    camera_frame_output_declarations,
    camera_frame_output_index,
    camera_measurement_authoring_schema,
    camera_measurement_default_role,
    camera_measurement_final_outputs,
    camera_measurement_roles,
    current_camera_monitor_selection,
    project_camera_measurement_outputs,
    project_camera_monitor_outputs,
)
from .finite import (
    PreparedFiniteCameraMeasurement,
    bind_finite_camera_measurement,
    prepare_finite_camera_measurement,
)
from .monitor import (
    CameraMonitorLiveDataset,
    CameraMonitorViewPort,
    CameraMonitorViewSpec,
    PreparedLiveCameraMeasurement,
    prepare_live_camera_measurement,
)

__all__ = [
    "CAMERA_FRAME_OUTPUT_CONTRACT_ID",
    "CAMERA_MEASUREMENT_DEFINITION",
    "CAMERA_MEASUREMENT_KEY",
    "CAMERA_MEASUREMENT_ROLE_ORDER",
    "DEFAULT_CAMERA_FRAMES_PER_CYCLE",
    "DEFAULT_CAMERA_MEASUREMENT_REPEAT",
    "DEFAULT_CAMERA_MEASUREMENT_ROLE",
    "DEFAULT_CAMERA_MONITOR_HISTORY_CYCLES",
    "MINIMUM_CAMERA_FRAMES_PER_CYCLE",
    "MINIMUM_CAMERA_MEASUREMENT_REPEAT",
    "CameraCaptureBindingRequest",
    "CameraMeasurementDescriptor",
    "CameraMeasurementRequest",
    "CameraMonitorLiveDataset",
    "CameraMonitorViewPort",
    "CameraMonitorViewSpec",
    "PreparedFiniteCameraMeasurement",
    "PreparedLiveCameraMeasurement",
    "bind_camera_measurement",
    "bind_finite_camera_measurement",
    "build_camera_measurement_request_from_authoring",
    "camera_frame_output_declarations",
    "camera_frame_output_index",
    "camera_measurement_authoring_schema",
    "camera_measurement_default_role",
    "camera_measurement_final_outputs",
    "camera_measurement_roles",
    "current_camera_monitor_selection",
    "prepare_finite_camera_measurement",
    "prepare_live_camera_measurement",
    "project_camera_measurement_outputs",
    "project_camera_monitor_outputs",
]
