"""Vivado/VIO runtime pulse-streamer backend for the FPGA computer.

The control computer sends a ``PulseSequence`` over RPyC.  The FPGA computer
compiles it into a ``RuntimeSequenceProgram`` and this backend uploads the
resulting edge table to a fixed pulse-streamer bitstream.
"""

from __future__ import annotations

from argparse import ArgumentParser
from dataclasses import dataclass
from pathlib import Path
import json
import os
import subprocess
import time
from typing import Mapping, Sequence

from .sequencer import RuntimeSequenceProgram
from ..timing import channel_names
from ..timing.verilog import CONTROL_PORTS, safe_identifier


DEFAULT_CHANNELS = ["trap", "cooling", "probe", "qcm_trigger"]
DEFAULT_VIO_FILTER = 'CELL_NAME=~"*vio*"'
DEFAULT_MAX_EDGES = 1024
DEFAULT_TICK_WIDTH = 32


@dataclass(frozen=True)
class PulseStreamerProbeNames:
    """Names of VIO probes connected to ``zlc_pulse_streamer``."""

    reset: str = "zlc_reset"
    start: str = "zlc_start"
    prog_we: str = "zlc_prog_we"
    prog_addr: str = "zlc_prog_addr"
    prog_tick: str = "zlc_prog_tick"
    prog_mask: str = "zlc_prog_mask"
    prog_count: str = "zlc_prog_count"
    running: str = "zlc_running"
    done: str = "zlc_done"


@dataclass(frozen=True)
class PulseStreamerHDLFiles:
    core_path: Path
    top_example_path: Path
    manifest_path: Path


def validate_pulse_streamer_program(
    program: RuntimeSequenceProgram,
    *,
    max_edges: int = DEFAULT_MAX_EDGES,
    tick_width: int = DEFAULT_TICK_WIDTH,
    channel_count: int | None = None,
) -> None:
    """Validate that a runtime edge table fits the fixed FPGA streamer."""

    max_edges = _positive_int(max_edges, "max_edges")
    tick_width = _positive_int(tick_width, "tick_width")
    channel_count = len(program.channels) if channel_count is None else _positive_int(channel_count, "channel_count")
    if len(set(program.channels)) != len(program.channels):
        raise ValueError("program channels must be unique.")
    if len(program.ticks) != len(program.masks):
        raise ValueError("program ticks and masks must have the same length.")
    if len(program.ticks) > max_edges:
        raise ValueError(f"program has {len(program.ticks)} edges, but the FPGA streamer only accepts {max_edges}.")
    if len(program.channels) > channel_count:
        raise ValueError(f"program uses {len(program.channels)} channels, but the FPGA streamer has {channel_count}.")
    tick_limit = (1 << tick_width) - 1
    mask_limit = (1 << channel_count) - 1
    last_tick = -1
    for tick in program.ticks:
        tick = int(tick)
        if tick <= last_tick:
            raise ValueError("program ticks must be strictly increasing.")
        if tick < 0 or tick > tick_limit:
            raise ValueError(f"program tick {tick} does not fit {tick_width} bits.")
        last_tick = tick
    for mask in program.masks:
        mask = int(mask)
        if mask < 0 or mask > mask_limit:
            raise ValueError(f"program mask {mask} does not fit {channel_count} channels.")
    if program.masks and int(program.masks[-1]) != 0:
        raise ValueError("program final mask must be 0 so the streamer returns to a safe idle state.")


def generate_pulse_streamer_core(
    *,
    module_name: str = "zlc_pulse_streamer",
    channel_count: int = len(DEFAULT_CHANNELS),
    max_edges: int = DEFAULT_MAX_EDGES,
    tick_width: int = DEFAULT_TICK_WIDTH,
) -> str:
    """Return synthesizable Verilog for a runtime edge-table pulse streamer."""

    module_name = safe_identifier(module_name)
    channel_count = _positive_int(channel_count, "channel_count")
    tick_width = _positive_int(tick_width, "tick_width")
    edge_addr_width = _edge_addr_width(max_edges)
    actual_edges = 1 << edge_addr_width
    return f"""`timescale 1ns / 1ps
// Generated by Zou_lab_control.neutral_atom.devices.fpga_pulse_streamer.
// Runtime-programmable edge-table pulse streamer.

module {module_name} #(
    parameter integer CHANNEL_COUNT = {channel_count},
    parameter integer EDGE_ADDR_WIDTH = {edge_addr_width},
    parameter integer TICK_WIDTH = {tick_width}
)(
    input wire clk,
    input wire reset,
    input wire start,
    input wire prog_we,
    input wire [EDGE_ADDR_WIDTH-1:0] prog_addr,
    input wire [TICK_WIDTH-1:0] prog_tick,
    input wire [CHANNEL_COUNT-1:0] prog_mask,
    input wire [EDGE_ADDR_WIDTH:0] prog_count,
    output wire [CHANNEL_COUNT-1:0] out,
    output reg running = 1'b0,
    output reg done = 1'b0
);

    localparam integer MAX_EDGES = {actual_edges};

    reg [TICK_WIDTH-1:0] tick_mem [0:MAX_EDGES-1];
    reg [CHANNEL_COUNT-1:0] mask_mem [0:MAX_EDGES-1];

    reg [CHANNEL_COUNT-1:0] state_mask = {{CHANNEL_COUNT{{1'b0}}}};
    reg [TICK_WIDTH-1:0] time_count = {{TICK_WIDTH{{1'b0}}}};
    reg [EDGE_ADDR_WIDTH:0] edge_index = {{(EDGE_ADDR_WIDTH + 1){{1'b0}}}};
    reg [EDGE_ADDR_WIDTH:0] active_count = {{(EDGE_ADDR_WIDTH + 1){{1'b0}}}};

    reg start_sync = 1'b0;
    reg start_prev = 1'b0;
    reg prog_we_sync = 1'b0;
    reg prog_we_prev = 1'b0;

    wire start_edge = start_sync && !start_prev;
    wire prog_we_edge = prog_we_sync && !prog_we_prev;
    wire [TICK_WIDTH-1:0] final_tick = (active_count == 0) ? {{TICK_WIDTH{{1'b0}}}} : tick_mem[active_count[EDGE_ADDR_WIDTH-1:0] - 1'b1];
    wire [EDGE_ADDR_WIDTH-1:0] edge_addr = edge_index[EDGE_ADDR_WIDTH-1:0];

    assign out = state_mask;

    always @(posedge clk) begin
        start_sync <= start;
        start_prev <= start_sync;
        prog_we_sync <= prog_we;
        prog_we_prev <= prog_we_sync;

        if (prog_we_edge) begin
            tick_mem[prog_addr] <= prog_tick;
            mask_mem[prog_addr] <= prog_mask;
        end

        if (reset) begin
            running <= 1'b0;
            done <= 1'b0;
            state_mask <= {{CHANNEL_COUNT{{1'b0}}}};
            time_count <= {{TICK_WIDTH{{1'b0}}}};
            edge_index <= {{(EDGE_ADDR_WIDTH + 1){{1'b0}}}};
            active_count <= {{(EDGE_ADDR_WIDTH + 1){{1'b0}}}};
        end else if (start_edge && !running) begin
            running <= (prog_count != 0);
            done <= (prog_count == 0);
            state_mask <= {{CHANNEL_COUNT{{1'b0}}}};
            time_count <= {{TICK_WIDTH{{1'b0}}}};
            edge_index <= {{(EDGE_ADDR_WIDTH + 1){{1'b0}}}};
            active_count <= prog_count;
        end else if (running) begin
            if (edge_index < active_count && time_count == tick_mem[edge_addr]) begin
                state_mask <= mask_mem[edge_addr];
                edge_index <= edge_index + 1'b1;
            end

            if (time_count >= final_tick) begin
                running <= 1'b0;
                done <= 1'b1;
                state_mask <= {{CHANNEL_COUNT{{1'b0}}}};
            end else begin
                time_count <= time_count + 1'b1;
            end
        end
    end
endmodule
"""


def generate_pulse_streamer_top_example(
    *,
    channels: Sequence[str] = DEFAULT_CHANNELS,
    core_module_name: str = "zlc_pulse_streamer",
    top_module_name: str = "zlc_pulse_streamer_top_example",
    max_edges: int = DEFAULT_MAX_EDGES,
    tick_width: int = DEFAULT_TICK_WIDTH,
    probe_names: PulseStreamerProbeNames | None = None,
) -> str:
    """Return an example top module showing the VIO probe contract."""

    channels = list(channel_names(channels, "channels"))
    core_module_name = safe_identifier(core_module_name)
    top_module_name = safe_identifier(top_module_name)
    probe_names = probe_names or PulseStreamerProbeNames()
    reserved = {
        *CONTROL_PORTS,
        "out",
        "zlc_streamer_i",
        "zlc_vio_i",
        "zlc_running_led",
        "zlc_done_led",
        *(safe_identifier(name) for name in probe_names.__dict__.values()),
    }
    safe_channels = _safe_channel_identifiers(channels, reserved=reserved)
    edge_addr_width = _edge_addr_width(max_edges)
    assigns = "\n".join(f"    assign {name} = out[{index}];" for index, name in enumerate(safe_channels))
    outputs = "\n".join(f"    output wire {name}," for name in safe_channels)
    return f"""`timescale 1ns / 1ps
// Example top-level wrapper for zlc_pulse_streamer.
// Create a Vivado VIO IP named vio_0 with these probes:
//   probe_out0 {probe_names.reset}      width 1
//   probe_out1 {probe_names.start}      width 1
//   probe_out2 {probe_names.prog_we}    width 1
//   probe_out3 {probe_names.prog_addr}  width {edge_addr_width}
//   probe_out4 {probe_names.prog_tick}  width {tick_width}
//   probe_out5 {probe_names.prog_mask}  width {len(channels)}
//   probe_out6 {probe_names.prog_count} width {edge_addr_width + 1}
//   probe_in0  {probe_names.running}    width 1
//   probe_in1  {probe_names.done}       width 1

module {top_module_name}(
    input wire clk,
{outputs}
    output wire zlc_running_led,
    output wire zlc_done_led
);

    wire {probe_names.reset};
    wire {probe_names.start};
    wire {probe_names.prog_we};
    wire [{edge_addr_width - 1}:0] {probe_names.prog_addr};
    wire [{tick_width - 1}:0] {probe_names.prog_tick};
    wire [{len(channels) - 1}:0] {probe_names.prog_mask};
    wire [{edge_addr_width}:0] {probe_names.prog_count};
    wire [{len(channels) - 1}:0] out;
    wire {probe_names.running};
    wire {probe_names.done};

{assigns}
    assign zlc_running_led = {probe_names.running};
    assign zlc_done_led = {probe_names.done};

    {core_module_name} #(
        .CHANNEL_COUNT({len(channels)}),
        .EDGE_ADDR_WIDTH({edge_addr_width}),
        .TICK_WIDTH({tick_width})
    ) zlc_streamer_i (
        .clk(clk),
        .reset({probe_names.reset}),
        .start({probe_names.start}),
        .prog_we({probe_names.prog_we}),
        .prog_addr({probe_names.prog_addr}),
        .prog_tick({probe_names.prog_tick}),
        .prog_mask({probe_names.prog_mask}),
        .prog_count({probe_names.prog_count}),
        .out(out),
        .running({probe_names.running}),
        .done({probe_names.done})
    );

    vio_0 zlc_vio_i (
        .clk(clk),
        .probe_in0({probe_names.running}),
        .probe_in1({probe_names.done}),
        .probe_out0({probe_names.reset}),
        .probe_out1({probe_names.start}),
        .probe_out2({probe_names.prog_we}),
        .probe_out3({probe_names.prog_addr}),
        .probe_out4({probe_names.prog_tick}),
        .probe_out5({probe_names.prog_mask}),
        .probe_out6({probe_names.prog_count})
    );
endmodule
"""


def write_pulse_streamer_hdl_bundle(
    output_dir: str | Path,
    *,
    channels: Sequence[str] = DEFAULT_CHANNELS,
    core_module_name: str = "zlc_pulse_streamer",
    top_module_name: str = "zlc_pulse_streamer_top_example",
    max_edges: int = DEFAULT_MAX_EDGES,
    tick_width: int = DEFAULT_TICK_WIDTH,
) -> PulseStreamerHDLFiles:
    """Write the pulse-streamer core, an example top, and a manifest."""

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    channels = list(channel_names(channels, "channels"))
    core_path = output_dir / f"{safe_identifier(core_module_name)}.v"
    top_path = output_dir / f"{safe_identifier(top_module_name)}.v"
    manifest_path = output_dir / "zlc_pulse_streamer.manifest.json"
    core_path.write_text(
        generate_pulse_streamer_core(
            module_name=core_module_name,
            channel_count=len(channels),
            max_edges=max_edges,
            tick_width=tick_width,
        ),
        encoding="utf-8",
        newline="\n",
    )
    top_path.write_text(
        generate_pulse_streamer_top_example(
            channels=channels,
            core_module_name=core_module_name,
            top_module_name=top_module_name,
            max_edges=max_edges,
            tick_width=tick_width,
        ),
        encoding="utf-8",
        newline="\n",
    )
    manifest = {
        "schema": "Zou_lab_control.neutral_atom.PulseStreamerHDL",
        "version": 1,
        "channels": channels,
        "max_edges": int(max_edges),
        "edge_addr_width": _edge_addr_width(max_edges),
        "tick_width": int(tick_width),
        "core": core_path.name,
        "top_example": top_path.name,
        "probe_names": PulseStreamerProbeNames().__dict__,
    }
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8", newline="\n")
    return PulseStreamerHDLFiles(core_path, top_path, manifest_path)


def write_vivado_pulse_streamer_tcl(
    path: str | Path,
    action: str,
    *,
    program: RuntimeSequenceProgram | None = None,
    project: str | None = None,
    bitstream: str | None = None,
    probes: str | None = None,
    vio_filter: str = DEFAULT_VIO_FILTER,
    program_on_run: str | None = None,
    probe_names: PulseStreamerProbeNames | None = None,
    max_edges: int = DEFAULT_MAX_EDGES,
    tick_width: int = DEFAULT_TICK_WIDTH,
    channel_count: int | None = None,
    timeout: float | None = None,
    poll_interval: float = 0.02,
) -> Path:
    """Write a Vivado Tcl action for the runtime pulse streamer."""

    action = _normalize_action(action)
    probe_names = probe_names or PulseStreamerProbeNames()
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    if program is not None:
        validate_pulse_streamer_program(program, max_edges=max_edges, tick_width=tick_width, channel_count=channel_count)
    channel_count = len(program.channels) if channel_count is None and program is not None else _positive_int(channel_count or len(DEFAULT_CHANNELS), "channel_count")

    lines = _vivado_common_tcl(
        project=project,
        bitstream=bitstream,
        probes=probes,
        vio_filter=vio_filter,
        program_on_run=program_on_run,
        probe_names=probe_names,
    )
    if action == "prepare":
        if program is None:
            raise ValueError("prepare requires a RuntimeSequenceProgram.")
        lines.extend(_prepare_tcl(program, probe_names=probe_names))
    elif action == "fire":
        lines.extend(_fire_tcl(probe_names=probe_names))
    elif action == "wait_done":
        lines.extend(_wait_done_tcl(probe_names=probe_names, timeout=timeout, poll_interval=poll_interval))
    elif action in {"safe_state", "abort"}:
        lines.extend(_safe_state_tcl(probe_names=probe_names))
    else:
        raise ValueError(f"unknown pulse-streamer action {action!r}.")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def run_action(
    action: str,
    *,
    program_path: str | Path | None = None,
    state_dir: str | Path | None = None,
    vivado: str = "vivado",
    dry_run: bool = False,
    timeout: float | None = None,
    max_edges: int | None = None,
    tick_width: int | None = None,
    channel_count: int | None = None,
) -> Path | None:
    """Run one pulse-streamer action from a sequencer-server command."""

    action = _normalize_action(action)
    state = Path(state_dir or os.environ.get("ZLC_STATE_DIR", "."))
    state.mkdir(parents=True, exist_ok=True)
    program = _read_program(program_path) if action == "prepare" else None
    if action == "wait_done" and timeout is None:
        timeout = _optional_float(os.environ.get("ZLC_TIMEOUT"))
    max_edges = _env_int("ZLC_PS_MAX_EDGES", DEFAULT_MAX_EDGES) if max_edges is None else max_edges
    tick_width = _env_int("ZLC_PS_TICK_WIDTH", DEFAULT_TICK_WIDTH) if tick_width is None else tick_width
    if channel_count is None:
        channel_count = _env_int("ZLC_PS_CHANNEL_COUNT", len(program.channels) if program is not None else len(DEFAULT_CHANNELS))
    tcl_path = write_vivado_pulse_streamer_tcl(
        state / f"pulse_streamer_{action}.tcl",
        action,
        program=program,
        project=_env_first("ZLC_PS_VIVADO_PROJECT", "ZLC_VIVADO_PROJECT"),
        bitstream=_env_first("ZLC_PS_VIVADO_BIT", "ZLC_VIVADO_BIT"),
        probes=_env_first("ZLC_PS_VIVADO_LTX", "ZLC_VIVADO_LTX"),
        vio_filter=os.environ.get("ZLC_PS_VIO_FILTER", os.environ.get("ZLC_VIO_FILTER", DEFAULT_VIO_FILTER)),
        program_on_run=_env_first("ZLC_PS_VIVADO_PROGRAM_ON_RUN", "ZLC_VIVADO_PROGRAM_ON_RUN"),
        max_edges=max_edges,
        tick_width=tick_width,
        channel_count=channel_count,
        timeout=timeout,
    )
    if dry_run:
        return tcl_path
    result = _run_vivado(vivado, tcl_path, state=state, timeout=None)
    log_path = state / f"pulse_streamer_{action}.log"
    log_path.write_text(result.stdout, encoding="utf-8", errors="replace")
    if result.returncode != 0:
        raise RuntimeError(f"pulse-streamer {action} failed with code {result.returncode}. See {log_path}.")
    if action == "fire":
        (state / "pulse_streamer_fire_time.txt").write_text(str(time.monotonic()), encoding="utf-8")
    return tcl_path


def build_arg_parser() -> ArgumentParser:
    parser = ArgumentParser(description="Prepare/fire a runtime-programmable FPGA pulse streamer.")
    parser.add_argument("action", choices=["prepare", "fire", "wait_done", "safe_state", "abort", "generate_hdl"], nargs="?", default=None)
    parser.add_argument("--program", default=None, help="RuntimeSequenceProgram JSON path. Defaults to ZLC_SEQUENCE_PROGRAM.")
    parser.add_argument("--state-dir", default=None, help="State/log directory. Defaults to ZLC_STATE_DIR.")
    parser.add_argument("--vivado", default=os.environ.get("ZLC_PS_VIVADO_BIN", os.environ.get("ZLC_VIVADO_BIN", "vivado")))
    parser.add_argument("--timeout", type=float, default=None)
    parser.add_argument("--dry-run", action="store_true", help="Only write the generated Tcl file.")
    parser.add_argument("--max-edges", type=int, default=None)
    parser.add_argument("--tick-width", type=int, default=None)
    parser.add_argument("--channel-count", type=int, default=None)
    parser.add_argument("--output-dir", default="generated_pulse_streamer")
    parser.add_argument("--channels", nargs="+", default=DEFAULT_CHANNELS)
    return parser


def main(argv=None) -> int:
    args = build_arg_parser().parse_args(argv)
    action = args.action or os.environ.get("ZLC_SEQUENCER_ACTION", "prepare")
    if action == "generate_hdl":
        files = write_pulse_streamer_hdl_bundle(
            args.output_dir,
            channels=args.channels,
            max_edges=args.max_edges or _env_int("ZLC_PS_MAX_EDGES", DEFAULT_MAX_EDGES),
            tick_width=args.tick_width or _env_int("ZLC_PS_TICK_WIDTH", DEFAULT_TICK_WIDTH),
        )
        print(files.core_path)
        print(files.top_example_path)
        print(files.manifest_path)
        return 0
    run_action(
        action,
        program_path=args.program,
        state_dir=args.state_dir,
        vivado=args.vivado,
        dry_run=args.dry_run,
        timeout=args.timeout,
        max_edges=args.max_edges,
        tick_width=args.tick_width,
        channel_count=args.channel_count,
    )
    return 0


def _vivado_common_tcl(
    *,
    project: str | None,
    bitstream: str | None,
    probes: str | None,
    vio_filter: str,
    program_on_run: str | None,
    probe_names: PulseStreamerProbeNames,
) -> list[str]:
    project_line = "set project [env_or ZLC_PS_VIVADO_PROJECT [env_or ZLC_VIVADO_PROJECT \"\"]]" if project is None else f"set project {{{project}}}"
    bitstream_line = "set bitstream [env_or ZLC_PS_VIVADO_BIT [env_or ZLC_VIVADO_BIT \"\"]]" if bitstream is None else f"set bitstream {{{bitstream}}}"
    probes_line = "set probes [env_or ZLC_PS_VIVADO_LTX [env_or ZLC_VIVADO_LTX \"\"]]" if probes is None else f"set probes {{{probes}}}"
    program_line = (
        "set program_on_run [env_or ZLC_PS_VIVADO_PROGRAM_ON_RUN [env_or ZLC_VIVADO_PROGRAM_ON_RUN \"0\"]]"
        if program_on_run is None
        else f"set program_on_run {{{program_on_run}}}"
    )
    return [
        "proc env_or {name default} {",
        "    if {[info exists ::env($name)]} { return $::env($name) }",
        "    return $default",
        "}",
        project_line,
        bitstream_line,
        probes_line,
        f"set vio_filter {{{vio_filter}}}",
        program_line,
        "if {$project ne \"\" && [file exists $project]} { open_project $project }",
        "open_hw_manager",
        "connect_hw_server -allow_non_jtag",
        "open_hw_target",
        "set device [lindex [get_hw_devices] 0]",
        "if {$device eq \"\"} { error \"No Vivado hardware device found.\" }",
        "if {$program_on_run ne \"0\" && $bitstream ne \"\" && [file exists $bitstream]} {",
        "    set_property PROGRAM.FILE $bitstream $device",
        "    if {$probes ne \"\" && [file exists $probes]} {",
        "        set_property PROBES.FILE $probes $device",
        "        set_property FULL_PROBES.FILE $probes $device",
        "    }",
        "    program_hw_devices $device",
        "    refresh_hw_device $device",
        "} elseif {$probes ne \"\" && [file exists $probes]} {",
        "    set_property PROBES.FILE $probes $device",
        "    set_property FULL_PROBES.FILE $probes $device",
        "    refresh_hw_device $device",
        "}",
        "set available_vios [get_hw_vios -of_objects $device]",
        "set vio [lindex [get_hw_vios -of_objects $device -filter $vio_filter] 0]",
        "if {$vio eq \"\"} {",
        "    puts \"Available VIO cores:\"",
        "    foreach candidate $available_vios {",
        "        puts \"  NAME=[get_property NAME $candidate] CELL_NAME=[get_property CELL_NAME $candidate]\"",
        "    }",
        "    error \"No VIO core matched filter '$vio_filter'.\"",
        "}",
        "proc zlc_list_probes {vio} {",
        "    puts \"Available probes on matched VIO:\"",
        "    foreach candidate [get_hw_probes -of_objects $vio] {",
        "        set line \"\"",
        "        foreach prop {NAME PROBE_TYPE DIRECTION INPUT_VALUE OUTPUT_VALUE WIDTH} {",
        "            if {![catch {get_property $prop $candidate} value]} { append line \" $prop=$value\" }",
        "        }",
        "        puts \"  $line\"",
        "    }",
        "}",
        "proc zlc_probe {vio name} {",
        "    set probe [lindex [get_hw_probes $name -of_objects $vio] 0]",
        "    if {$probe eq \"\"} {",
        "        zlc_list_probes $vio",
        "        error \"VIO probe '$name' was not found.\"",
        "    }",
        "    return $probe",
        "}",
        "proc zlc_set_probe {vio name value} {",
        "    set probe [zlc_probe $vio $name]",
        "    set_property OUTPUT_VALUE_RADIX UNSIGNED $probe",
        "    set_property OUTPUT_VALUE $value $probe",
        "    commit_hw_vio $probe",
        "    puts \"ZLC pulse-streamer VIO: $name=$value\"",
        "}",
        "proc zlc_read_probe {vio name} {",
        "    refresh_hw_vio $vio",
        "    set probe [zlc_probe $vio $name]",
        "    return [get_property INPUT_VALUE $probe]",
        "}",
        f"set zlc_reset_probe {{{probe_names.reset}}}",
        f"set zlc_start_probe {{{probe_names.start}}}",
        f"set zlc_prog_we_probe {{{probe_names.prog_we}}}",
        f"set zlc_prog_addr_probe {{{probe_names.prog_addr}}}",
        f"set zlc_prog_tick_probe {{{probe_names.prog_tick}}}",
        f"set zlc_prog_mask_probe {{{probe_names.prog_mask}}}",
        f"set zlc_prog_count_probe {{{probe_names.prog_count}}}",
        f"set zlc_running_probe {{{probe_names.running}}}",
        f"set zlc_done_probe {{{probe_names.done}}}",
    ]


def _prepare_tcl(program: RuntimeSequenceProgram, *, probe_names: PulseStreamerProbeNames) -> list[str]:
    lines = [
        "zlc_set_probe $vio $zlc_reset_probe 1",
        "zlc_set_probe $vio $zlc_start_probe 0",
        "zlc_set_probe $vio $zlc_prog_we_probe 0",
        f"zlc_set_probe $vio $zlc_prog_count_probe {len(program.ticks)}",
    ]
    for index, (tick, mask) in enumerate(zip(program.ticks, program.masks)):
        lines.extend(
            [
                f"zlc_set_probe $vio $zlc_prog_addr_probe {index}",
                f"zlc_set_probe $vio $zlc_prog_tick_probe {int(tick)}",
                f"zlc_set_probe $vio $zlc_prog_mask_probe {int(mask)}",
                "zlc_set_probe $vio $zlc_prog_we_probe 1",
                "zlc_set_probe $vio $zlc_prog_we_probe 0",
            ]
        )
    lines.extend(
        [
            "zlc_set_probe $vio $zlc_reset_probe 0",
            f"puts \"ZLC pulse-streamer prepared sequence {program.sequence_id} with {len(program.ticks)} edges\"",
        ]
    )
    return lines


def _fire_tcl(*, probe_names: PulseStreamerProbeNames) -> list[str]:
    return [
        "zlc_set_probe $vio $zlc_reset_probe 0",
        "zlc_set_probe $vio $zlc_start_probe 0",
        "zlc_set_probe $vio $zlc_start_probe 1",
        "zlc_set_probe $vio $zlc_start_probe 0",
        "puts \"ZLC pulse-streamer start edge sent\"",
    ]


def _wait_done_tcl(*, probe_names: PulseStreamerProbeNames, timeout: float | None, poll_interval: float) -> list[str]:
    timeout_expr = str(float(timeout)) if timeout is not None else "[env_or ZLC_TIMEOUT 10.0]"
    poll_ms = max(1, int(round(float(poll_interval) * 1000)))
    return [
        f"set timeout_s {timeout_expr}",
        "set deadline [expr {[clock milliseconds] + int(1000.0 * double($timeout_s))}]",
        "while {1} {",
        "    set done_value [zlc_read_probe $vio $zlc_done_probe]",
        "    if {$done_value ne \"0\"} {",
        "        puts \"ZLC pulse-streamer done\"",
        "        break",
        "    }",
        "    if {[clock milliseconds] > $deadline} { error \"ZLC pulse-streamer wait_done timed out.\" }",
        f"    after {poll_ms}",
        "}",
    ]


def _safe_state_tcl(*, probe_names: PulseStreamerProbeNames) -> list[str]:
    return [
        "zlc_set_probe $vio $zlc_start_probe 0",
        "zlc_set_probe $vio $zlc_prog_we_probe 0",
        "zlc_set_probe $vio $zlc_reset_probe 1",
        "puts \"ZLC pulse-streamer safe state requested\"",
    ]


def _read_program(program_path: str | Path | None) -> RuntimeSequenceProgram:
    path = Path(program_path or os.environ["ZLC_SEQUENCE_PROGRAM"])
    return RuntimeSequenceProgram.from_dict(json.loads(path.read_text(encoding="utf-8")))


def _run_vivado(vivado: str, tcl_path: Path, *, state: Path, timeout: float | None):
    try:
        return subprocess.run(
            [vivado, "-mode", "batch", "-source", str(tcl_path)],
            cwd=state,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=timeout,
        )
    except FileNotFoundError as exc:
        log_path = state / f"{tcl_path.stem}.log"
        message = (
            f"Vivado executable was not found: {vivado!r}.\n"
            "Set ZLC_PS_VIVADO_BIN or ZLC_VIVADO_BIN to the full Vivado executable path."
        )
        log_path.write_text(message, encoding="utf-8", errors="replace")
        raise RuntimeError(f"pulse-streamer could not start Vivado. See {log_path}.") from exc


def _normalize_action(action: str) -> str:
    action = str(action).strip()
    return "safe_state" if action == "abort" else action


def _edge_addr_width(max_edges: int) -> int:
    max_edges = _positive_int(max_edges, "max_edges")
    return max(1, (max_edges - 1).bit_length())


def _safe_channel_identifiers(channels: Sequence[str], *, reserved: set[str]) -> list[str]:
    safe_channels = [safe_identifier(channel) for channel in channels]
    if len(set(safe_channels)) != len(safe_channels):
        raise ValueError("channel names collide after Verilog identifier sanitization.")
    collisions = sorted(set(safe_channels) & set(reserved))
    if collisions:
        raise ValueError(f"channel names collide with pulse-streamer top-level names: {collisions}")
    return safe_channels


def _positive_int(value, name: str) -> int:
    out = int(value)
    if out <= 0:
        raise ValueError(f"{name} must be positive.")
    return out


def _optional_float(value) -> float | None:
    if value is None or str(value).strip() == "":
        return None
    return float(value)


def _env_int(name: str, default: int) -> int:
    raw = os.environ.get(name)
    return int(default if raw is None or raw == "" else raw)


def _env_first(*names: str) -> str | None:
    for name in names:
        value = os.environ.get(name)
        if value:
            return value
    return None


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())


__all__ = [
    "DEFAULT_MAX_EDGES",
    "DEFAULT_TICK_WIDTH",
    "DEFAULT_VIO_FILTER",
    "PulseStreamerHDLFiles",
    "PulseStreamerProbeNames",
    "build_arg_parser",
    "generate_pulse_streamer_core",
    "generate_pulse_streamer_top_example",
    "main",
    "run_action",
    "validate_pulse_streamer_program",
    "write_pulse_streamer_hdl_bundle",
    "write_vivado_pulse_streamer_tcl",
]
