"""Stable headless frontend contracts with no implicit renderer or Qt import."""

from .curve_display import (
    CurveDisplayState,
    CurveViewportTransform,
    NumericDisplayAxis,
    NumericViewportTransform,
    curve_display_form_spec,
    curve_display_form_values,
    curve_display_from_form,
)
from .data_figure import DataFigure
from .display_range import DisplayRange, RelimMode
from .figure import (
    AxisViewRole,
    DatasetDescriptor,
    DatasetId,
    DisplayReduction,
    DisplayReductionMethod,
    EvaluatedProjectionIdentity,
    FigureDocument,
    FigureLayer,
    FigureSelection,
    FixedIndex,
    LatestNonempty,
    SourceViewBinding,
    SuggestionStatus,
    ViewContract,
    ViewIntent,
    ViewPreferences,
    ViewSpec,
    ViewSuggestion,
    contract_for,
    suggest_default_grid_view,
    suggest_fit_view,
    suggest_view,
    validate_view_spec,
)
from .figure_archive import FigureArchive, FigureDisplayState
from .figure_outputs import (
    AREA_DATA_OUTPUT,
    CROSS_DATA_OUTPUT,
    FigureAreaCommit,
    FigureCrossCommit,
    FigureDerivedSignal,
    FigureOutputPresentation,
)
from .figure_source import FigureSource
from .fit_editor import (
    FitAuthoringDraft,
    FitAuthoringOption,
    fit_spec_from_arguments,
    prepare_fit_authoring_options,
    reconcile_fit_authoring_draft,
    validate_fit_authoring_options,
)
from .form import FormChoice, FormFieldProps, FormSpec
from .histogram_display import (
    FacetedHistogramDisplayState,
    HistogramBinProjection,
    HistogramCellThresholds,
    HistogramDisplayState,
    HistogramViewportTransform,
    histogram_display_form_spec,
    histogram_display_form_values,
    histogram_display_from_form,
)
from .image_display import (
    ImageColormap,
    ImageDisplayState,
    image_display_form_spec,
    image_display_form_values,
    image_display_from_form,
)
from .image_view import ImageViewportTransform, NormalizedRectangle
from .meter_display import MeterDisplayState
from .plot_kind import PlotKind
from .plot_panel import (
    FigureIntent,
    PlotDisplayState,
    PlotPanelContract,
    PlotPanelSession,
    plot_panel_display_state,
)
from .plot_report import PlotReportDocument, plot_report_page
from .render import BoardFrame
from .selector import (
    CrossGesture,
    CurveInteractionIntent,
    CurveRangeGesture,
    CurveViewportCommit,
    HistogramInteractionIntent,
    HistogramRangeGesture,
    HistogramThresholdCommit,
    HistogramViewportCommit,
    ImageColorLimitsCommit,
    ImageInteractionCommit,
    ImageViewportCommit,
    PanelInteractionOrigin,
    RectangleGesture,
)

__all__ = [
    "AREA_DATA_OUTPUT",
    "AxisViewRole",
    "BoardFrame",
    "CROSS_DATA_OUTPUT",
    "CrossGesture",
    "CurveDisplayState",
    "CurveInteractionIntent",
    "CurveRangeGesture",
    "CurveViewportCommit",
    "CurveViewportTransform",
    "DataFigure",
    "DatasetDescriptor",
    "DatasetId",
    "DisplayRange",
    "DisplayReduction",
    "DisplayReductionMethod",
    "EvaluatedProjectionIdentity",
    "FacetedHistogramDisplayState",
    "FigureArchive",
    "FigureAreaCommit",
    "FigureCrossCommit",
    "FigureDerivedSignal",
    "FigureDisplayState",
    "FigureDocument",
    "FigureIntent",
    "FigureLayer",
    "FigureOutputPresentation",
    "FigureSelection",
    "FigureSource",
    "FitAuthoringDraft",
    "FitAuthoringOption",
    "FixedIndex",
    "FormChoice",
    "FormFieldProps",
    "FormSpec",
    "HistogramBinProjection",
    "HistogramCellThresholds",
    "HistogramDisplayState",
    "HistogramInteractionIntent",
    "HistogramRangeGesture",
    "HistogramThresholdCommit",
    "HistogramViewportCommit",
    "HistogramViewportTransform",
    "ImageColorLimitsCommit",
    "ImageColormap",
    "ImageDisplayState",
    "ImageInteractionCommit",
    "ImageViewportCommit",
    "ImageViewportTransform",
    "LatestNonempty",
    "MeterDisplayState",
    "NormalizedRectangle",
    "NumericDisplayAxis",
    "NumericViewportTransform",
    "PanelInteractionOrigin",
    "PlotDisplayState",
    "PlotKind",
    "PlotPanelContract",
    "PlotPanelSession",
    "PlotReportDocument",
    "RectangleGesture",
    "RelimMode",
    "SourceViewBinding",
    "SuggestionStatus",
    "ViewContract",
    "ViewIntent",
    "ViewPreferences",
    "ViewSpec",
    "ViewSuggestion",
    "contract_for",
    "curve_display_form_spec",
    "curve_display_form_values",
    "curve_display_from_form",
    "fit_spec_from_arguments",
    "histogram_display_form_spec",
    "histogram_display_form_values",
    "histogram_display_from_form",
    "image_display_form_spec",
    "image_display_form_values",
    "image_display_from_form",
    "plot_panel_display_state",
    "plot_report_page",
    "prepare_fit_authoring_options",
    "reconcile_fit_authoring_draft",
    "suggest_default_grid_view",
    "suggest_fit_view",
    "suggest_view",
    "validate_fit_authoring_options",
    "validate_view_spec",
]
