"""Tiny Verilog generator for ``PulseSequence`` edge tables."""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
from typing import Mapping, Sequence

from ..core.analysis import positive_int
from .sequence import PulseSequence, channel_names, positive_float


CONTROL_PORTS = ("clk", "reset", "start", "running", "done")


@dataclass(frozen=True)
class VerilogBuild:
    module_name: str
    clock_hz: float
    channels: list[str]
    ticks: list[int]
    masks: list[int]
    source: str
    source_sha256: str


@dataclass(frozen=True)
class VerilogFiles:
    verilog_path: Path
    manifest_path: Path
    xdc_path: Path | None = None


def generate_verilog(
    sequence: PulseSequence,
    *,
    channels: Sequence[str] | None = None,
    clock_hz: float = 50_000_000.0,
    module_name: str = "zlc_sequence",
) -> VerilogBuild:
    """Generate a small start/done edge-table sequencer module."""

    clock_hz = positive_float(clock_hz, "clock_hz")
    channels = list(sequence.channels if channels is None else channel_names(channels, "channels"))
    if not channels:
        raise ValueError("channels must not be empty.")
    safe_channels = [safe_identifier(channel) for channel in channels]
    if len(set(safe_channels)) != len(safe_channels):
        raise ValueError("channel names collide after Verilog identifier sanitization.")
    collisions = sorted(set(safe_channels) & set(CONTROL_PORTS))
    if collisions:
        raise ValueError(f"channel names collide with control ports: {collisions}")

    ticks, masks, channels = sequence.edges(clock_hz=clock_hz, channels=channels)
    if not ticks:
        ticks, masks = [1], [0]
    final_tick = max(ticks[-1], 1)
    tick_width = max(1, (final_tick + 1).bit_length())
    edge_width = max(1, len(ticks).bit_length())
    chan_width = len(channels)
    tick_rows = "\n".join(f"                {idx}: edge_tick = {tick_width}'d{tick};" for idx, tick in enumerate(ticks))
    mask_rows = "\n".join(f"                {idx}: edge_mask = {chan_width}'b{mask:0{chan_width}b};" for idx, mask in enumerate(masks))
    outputs = "\n".join(f"    output wire {name}," for name in safe_channels)
    assigns = "\n".join(f"    assign {name} = state_mask[{idx}];" for idx, name in enumerate(safe_channels))
    source = f"""`timescale 1ns / 1ps
// Generated by Zou_lab_control.neutral_atom.
// Sequence: {sequence.name}
// Clock: {clock_hz:g} Hz

module {safe_identifier(module_name)}(
    input wire clk,
    input wire reset,
    input wire start,
{outputs}
    output reg running,
    output reg done
);

    localparam integer EDGE_COUNT = {len(ticks)};
    localparam [{tick_width - 1}:0] FINAL_TICK = {tick_width}'d{final_tick};
    reg [{tick_width - 1}:0] time_count = 0;
    reg [{edge_width - 1}:0] edge_index = 0;
    reg [{chan_width - 1}:0] state_mask = {chan_width}'b0;
    reg [{tick_width - 1}:0] edge_tick;
    reg [{chan_width - 1}:0] edge_mask;
    reg start_prev = 1'b0;
    wire start_edge = start && !start_prev;

{assigns}

    always @(*) begin
        case (edge_index)
{tick_rows}
            default: edge_tick = FINAL_TICK;
        endcase
        case (edge_index)
{mask_rows}
            default: edge_mask = {chan_width}'b0;
        endcase
    end

    always @(posedge clk) begin
        if (reset) begin
            running <= 1'b0;
            done <= 1'b0;
            time_count <= 0;
            edge_index <= 0;
            state_mask <= {chan_width}'b0;
            start_prev <= 1'b0;
        end else begin
            start_prev <= start;
            if (start_edge && !running) begin
                running <= 1'b1;
                done <= 1'b0;
                time_count <= 0;
                edge_index <= 0;
                state_mask <= {chan_width}'b0;
            end else if (running) begin
                done <= 1'b0;
                if (time_count == edge_tick) begin
                    state_mask <= edge_mask;
                    if (edge_index < EDGE_COUNT - 1) begin
                        edge_index <= edge_index + 1'b1;
                    end
                end
                if (time_count >= FINAL_TICK) begin
                    running <= 1'b0;
                    done <= 1'b1;
                    state_mask <= {chan_width}'b0;
                end else begin
                    time_count <= time_count + 1'b1;
                end
            end else begin
                done <= 1'b0;
            end
        end
    end
endmodule
"""
    module = safe_identifier(module_name)
    return VerilogBuild(module, clock_hz, list(channels), list(ticks), list(masks), source, hashlib.sha256(source.encode("utf-8")).hexdigest())


def write_verilog_bundle(
    build: VerilogBuild,
    output_dir: str | Path,
    *,
    pin_map: Mapping[str, str] | None = None,
    filename: str | None = None,
) -> VerilogFiles:
    """Write ``.v``, a JSON manifest, and optional XDC pin constraints."""

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    verilog_path = output_dir / safe_filename(filename or f"{build.module_name}.v")
    manifest_path = output_dir / f"{build.module_name}.manifest.json"
    xdc_path = None
    verilog_path.write_text(build.source, encoding="utf-8", newline="\n")
    if pin_map is not None:
        xdc_path = output_dir / f"{build.module_name}.xdc"
        xdc_path.write_text(generate_xdc(pin_map), encoding="utf-8", newline="\n")
    manifest = {
        "module_name": build.module_name,
        "clock_hz": build.clock_hz,
        "channels": build.channels,
        "ticks": build.ticks,
        "masks": build.masks,
        "source_sha256": build.source_sha256,
        "verilog": verilog_path.name,
        "xdc": None if xdc_path is None else xdc_path.name,
    }
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8", newline="\n")
    return VerilogFiles(verilog_path, manifest_path, xdc_path)


def generate_xdc(pin_map: Mapping[str, str], *, iostandard: str = "LVCMOS33") -> str:
    if not isinstance(pin_map, Mapping) or not pin_map:
        raise ValueError("pin_map must be a non-empty mapping.")
    lines = ["# Generated by Zou_lab_control.neutral_atom"]
    for port, pin in pin_map.items():
        port = safe_identifier(str(port))
        pin = xdc_token(str(pin), f"pin for {port}")
        lines.append(f"set_property -dict {{PACKAGE_PIN {pin} IOSTANDARD {iostandard}}} [get_ports {port}]")
    return "\n".join(lines) + "\n"


def safe_identifier(name: str) -> str:
    text = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in str(name))
    if not text:
        text = "signal"
    if text[0].isdigit():
        text = f"sig_{text}"
    return text


def safe_filename(filename: str | Path) -> str:
    path = Path(filename)
    if path.drive or path.is_absolute() or len(path.parts) != 1 or path.name in {"", ".", ".."}:
        raise ValueError("filename must be a plain filename inside output_dir.")
    return path.name


def xdc_token(value: str, name: str) -> str:
    token = str(value).strip()
    if not token or any(ch.isspace() or ch in "{}[]();" for ch in token):
        raise ValueError(f"{name} is not a safe XDC token.")
    return token


__all__ = [
    "CONTROL_PORTS",
    "VerilogBuild",
    "VerilogFiles",
    "generate_verilog",
    "generate_xdc",
    "write_verilog_bundle",
]
