`timescale 1ns / 1ps
// Generated by Zou_lab_control.neutral_atom.
// Sequence: imaging
// Clock: 2.5e+08 Hz

module neutral_atom_sequence(
    input wire clk,
    input wire reset,
    input wire start,
    output wire trap,
    output wire cooling,
    output wire probe,
    output wire qcm_trigger,
    output wire camera_trigger,
    output wire trig,
    output wire pushout,
    output wire microwave,
    output reg running,
    output reg done
);

    localparam integer EDGE_COUNT = 6;
    localparam [19:0] FINAL_TICK = 20'd1030000;
    reg [19:0] time_count = 0;
    reg [2:0] edge_index = 0;
    reg [7:0] state_mask = 8'b0;
    reg [19:0] edge_tick;
    reg [7:0] edge_mask;
    reg start_prev = 1'b0;
    wire start_edge = start && !start_prev;

    assign trap = state_mask[0];
    assign cooling = state_mask[1];
    assign probe = state_mask[2];
    assign qcm_trigger = state_mask[3];
    assign camera_trigger = state_mask[4];
    assign trig = state_mask[5];
    assign pushout = state_mask[6];
    assign microwave = state_mask[7];

    always @(*) begin
        case (edge_index)
                0: edge_tick = 20'd0;
                1: edge_tick = 20'd500000;
                2: edge_tick = 20'd525000;
                3: edge_tick = 20'd530000;
                4: edge_tick = 20'd1025000;
                5: edge_tick = 20'd1030000;
            default: edge_tick = FINAL_TICK;
        endcase
        case (edge_index)
                0: edge_mask = 8'b00000011;
                1: edge_mask = 8'b00000001;
                2: edge_mask = 8'b00001101;
                3: edge_mask = 8'b00000101;
                4: edge_mask = 8'b00000001;
                5: edge_mask = 8'b00000000;
            default: edge_mask = 8'b0;
        endcase
    end

    always @(posedge clk) begin
        if (reset) begin
            running <= 1'b0;
            done <= 1'b0;
            time_count <= 0;
            edge_index <= 0;
            state_mask <= 8'b0;
            start_prev <= 1'b0;
        end else begin
            start_prev <= start;
            if (start_edge && !running) begin
                running <= 1'b1;
                done <= 1'b0;
                time_count <= 0;
                edge_index <= 0;
                state_mask <= 8'b0;
            end else if (running) begin
                done <= 1'b0;
                if (time_count == edge_tick) begin
                    state_mask <= edge_mask;
                    if (edge_index < EDGE_COUNT - 1) begin
                        edge_index <= edge_index + 1'b1;
                    end
                end
                if (time_count >= FINAL_TICK) begin
                    running <= 1'b0;
                    done <= 1'b1;
                    state_mask <= 8'b0;
                end else begin
                    time_count <= time_count + 1'b1;
                end
            end else begin
                done <= 1'b0;
            end
        end
    end
endmodule
