"""Headless, domain-neutral semantics for named multidimensional data."""

from importlib import import_module

from ._arrays import (
    immutable_array,
    immutable_bool_broadcast,
    is_intrinsically_immutable_array,
)
from ._diagnostic import exact_integer_text
from .axis import (
    COMPONENT,
    HISTOGRAM_BIN,
    MONITOR_HISTORY,
    READOUT_EVENT,
    REPEAT,
    SCALAR,
    SCALAR_AXIS,
    SCAN_POINT,
    SITE,
    SPATIAL_X,
    SPATIAL_Y,
    SPECTRAL,
    AxisId,
    AxisRoleId,
    AxisSpec,
    CoordinateFrameId,
)
from .codec import (
    axis_layout_from_tree,
    axis_layout_to_tree,
    axis_from_tree,
    axis_to_tree,
    dataset_schema_fingerprint,
    dataset_schema_from_tree,
    dataset_schema_to_tree,
    dataset_revision_ref_from_tree,
    dataset_revision_ref_to_tree,
    point_layout_from_tree,
    point_layout_to_tree,
    value_schema_fingerprint,
    value_schema_from_tree,
    value_schema_to_tree,
    validity_from_tree,
    validity_to_tree,
    TypedCodecError,
)
from .layout import AxisLayout, AxisLayoutMode, PointLayout
from .output_contract import (
    AUTHORITATIVE_AREA_SELECTION_PROJECTION_ID,
    projected_dataset_output_contract_id,
)
from .schema import (
    DatasetSchema,
    ValueSchema,
)
from .validity import (
    INVALID,
    VALID,
    CellValidity,
    ComponentValidity,
    DatasetComponentValidity,
    Invalid,
    RowComponentValidity,
    Valid,
    ValidityContract,
    ValidityMode,
)
from .value import (
    BlockId,
    DataBlock,
    DatasetRevision,
    DatasetRevisionRef,
    OwnedSnapshot,
    StreamGenerationId,
    Value,
    ValuePayloadContract,
    canonical_value_array,
    dataset_cell_value,
    expand_dataset_validity,
    expand_component_validity,
    expand_value_validity,
)
from .selection import (
    CoordinateRangeSelection,
    IndexRangeSelection,
    IndexSelection,
    Selection,
    resolve_outer_cell_selection,
    resolve_selection_indices,
    selection_for_outer_cell,
    selection_from_tree,
    selection_to_tree,
)
from .transform import (
    CommittedTransform,
    DataTransformSpec,
    MissingPolicy,
    ReductionMethod,
    ReductionSpec,
    TransformedData,
    TransformedSchema,
    ValidityPolicy,
    apply_transform,
    commit_transform,
    resolve_transformed_schema,
)
from .transform_codec import (
    committed_transform_from_tree,
    committed_transform_to_tree,
    data_transform_spec_from_tree,
    data_transform_spec_to_tree,
    transformed_schema_to_tree,
)
from .snapshot_projection import (
    materialize_component_dataset,
    materialize_dataset_acceptance_mask,
    materialize_dataset_selection,
    materialize_fit_parameter_snapshots,
    materialize_scalar_dataset,
)
from .fit import (
    BoundFit,
    FitBatchStatus,
    FitCancelled,
    FitCoordinateSource,
    FitDeadlineExceeded,
    FitModelDefinition,
    FitNumericPolicy,
    FitParameterConstraint,
    FitParameterDefinition,
    FitParameterDomain,
    FitResultBatch,
    FitSpec,
    ParameterUnitRelation,
    bind_fit,
    decode_fit_result_batch,
    decode_fit_spec,
    encode_fit_result_batch,
    encode_fit_spec,
    fit_model_catalog,
    fit_model_definition,
    fit_spec_from_tree,
    fit_spec_for,
    fit_spec_to_tree,
    suggest_fit_draft,
    validate_fit_result_source_binding,
)

_LAZY_EXPORTS = {
    "HistogramFitResult": ("histogram_fit", "HistogramFitResult"),
    "confidence_weighted_fidelity": (
        "histogram_fit",
        "confidence_weighted_fidelity",
    ),
    "fit_histogram": ("histogram_fit", "fit_histogram"),
}


def __getattr__(name: str):
    try:
        module_name, attribute_name = _LAZY_EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    value = getattr(import_module(f".{module_name}", __name__), attribute_name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_LAZY_EXPORTS))

__all__ = [
    "AUTHORITATIVE_AREA_SELECTION_PROJECTION_ID",
    "AxisId",
    "AxisLayout",
    "AxisLayoutMode",
    "AxisRoleId",
    "AxisSpec",
    "BlockId",
    "BoundFit",
    "COMPONENT",
    "CellValidity",
    "CommittedTransform",
    "ComponentValidity",
    "CoordinateFrameId",
    "DataBlock",
    "DataTransformSpec",
    "DatasetComponentValidity",
    "DatasetRevision",
    "DatasetRevisionRef",
    "DatasetSchema",
    "FitBatchStatus",
    "FitCancelled",
    "FitCoordinateSource",
    "FitDeadlineExceeded",
    "FitModelDefinition",
    "FitNumericPolicy",
    "FitParameterConstraint",
    "FitParameterDefinition",
    "FitParameterDomain",
    "FitResultBatch",
    "FitSpec",
    "HistogramFitResult",
    "INVALID",
    "HISTOGRAM_BIN",
    "MONITOR_HISTORY",
    "Invalid",
    "RowComponentValidity",
    "IndexRangeSelection",
    "IndexSelection",
    "immutable_array",
    "immutable_bool_broadcast",
    "is_intrinsically_immutable_array",
    "CoordinateRangeSelection",
    "MissingPolicy",
    "OwnedSnapshot",
    "ParameterUnitRelation",
    "PointLayout",
    "READOUT_EVENT",
    "REPEAT",
    "ReductionMethod",
    "ReductionSpec",
    "SCAN_POINT",
    "SCALAR",
    "SCALAR_AXIS",
    "SITE",
    "Selection",
    "SPATIAL_X",
    "SPATIAL_Y",
    "SPECTRAL",
    "StreamGenerationId",
    "TypedCodecError",
    "TransformedData",
    "TransformedSchema",
    "VALID",
    "Valid",
    "ValidityContract",
    "ValidityMode",
    "ValidityPolicy",
    "Value",
    "ValuePayloadContract",
    "ValueSchema",
    "axis_from_tree",
    "axis_layout_from_tree",
    "axis_layout_to_tree",
    "axis_to_tree",
    "apply_transform",
    "bind_fit",
    "commit_transform",
    "confidence_weighted_fidelity",
    "committed_transform_from_tree",
    "committed_transform_to_tree",
    "dataset_schema_fingerprint",
    "dataset_schema_from_tree",
    "dataset_schema_to_tree",
    "dataset_revision_ref_from_tree",
    "dataset_revision_ref_to_tree",
    "dataset_cell_value",
    "decode_fit_result_batch",
    "decode_fit_spec",
    "encode_fit_result_batch",
    "encode_fit_spec",
    "exact_integer_text",
    "resolve_transformed_schema",
    "materialize_component_dataset",
    "materialize_dataset_acceptance_mask",
    "materialize_dataset_selection",
    "materialize_fit_parameter_snapshots",
    "materialize_scalar_dataset",
    "resolve_outer_cell_selection",
    "resolve_selection_indices",
    "selection_for_outer_cell",
    "canonical_value_array",
    "expand_dataset_validity",
    "expand_component_validity",
    "expand_value_validity",
    "fit_model_catalog",
    "fit_histogram",
    "fit_model_definition",
    "fit_spec_from_tree",
    "fit_spec_for",
    "fit_spec_to_tree",
    "suggest_fit_draft",
    "point_layout_from_tree",
    "point_layout_to_tree",
    "projected_dataset_output_contract_id",
    "data_transform_spec_from_tree",
    "data_transform_spec_to_tree",
    "selection_from_tree",
    "selection_to_tree",
    "value_schema_fingerprint",
    "value_schema_from_tree",
    "value_schema_to_tree",
    "validity_from_tree",
    "validity_to_tree",
    "validate_fit_result_source_binding",
]
